name: Run JMeter Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JMeter (latest)
        run: |
          JMETER_VERSION=5.6.3
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xzf apache-jmeter-$JMETER_VERSION.tgz
          mv apache-jmeter-$JMETER_VERSION jmeter

      - name: Run JMeter Test
        run: |
          ./jmeter/bin/jmeter -n -t GithubTest.jmx -l results.jtl

      - name: Generate HTML Report
        run: |
          ./jmeter/bin/jmeter -g results.jtl -o report

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: report
